tpls = {};

tpls.tpls_cal_years = '<a href="javascript:;" class="years-picker-range">1980年-1995年</a><ul class="clearfix border-box table-condensed"><% _.each(years, function(year){ %><li class="date-cell year-cell" data-year=<%= year.calendar%> ><span class="solar cal-year"><%= year.calendar%></span><span class="lunar"><%= year.lunar%></span></li><%})%><div class="clearfix"></div></ul>';

tpls.tpls_cal_months = '<ul class="month-cell-container clearfix border-box table-condensed"><% _.each(months, function(month,i){%><li class="date-cell month-cell" data-month=<%=(i+1)%> ><span class="solar"><%=(month.solarOrLunar)%></span><span class="lunar"><%=month.ganzhi%></span></li><%})%></ul>';

tpls.tpls_cal_days = '<table class="table-condensed"><thead><tr><th width="14.28%">一</th><th width="14.28%">二</th><th width="14.28%">三</th><th width="14.28%">四</th><th width="14.28%">五</th><th width="14.28%">六</th><th width="14.28%">日</th></tr></thead><tbody></tbody></table>';

tpls.tpls_cal_hours = '<div class="condensed-bd"><div class="condensed-bd-item condensed-bd-simple"><ul class="clearfix border-box table-condensed table-condensed-hours"><% _.each(hours,function(hour,i){ %><li class="date-cell hour-cell" data-hour=<%= i%> ><p class="solar"><%= hour.calendar%></p><p class="lunar"><%= hour.ganzhi%></p></li><% })%><div class="clearfix"></div></ul></div><div class="condensed-bd-item condensed-bd-detail" style="display: none"><select name="selectH" class="selectH"></select>时<select name="selectM" class="selectM"></select>分<select name="selectS" class="selectS"></select>秒</div></div>';

tpls.tpls_cal_ctrlBar = '<div class="cal-ctrl-bar control-wrap clearfix"><% if(hasGanZhi){ %><div class="lunar-ganzhi fn-left"><ul class="clearfix ganzhi-info"><li class="cal-picker-ctrl" data-send="year" data-fill="GanZhiYear"></li><li class="cal-picker-ctrl" data-send="month" data-fill="GanZhiMonth"></li><li class="cal-picker-ctrl" data-send="day" data-fill="GanZhiDay"></li><li class="cal-picker-ctrl" data-send="hour" data-fill="GanZhiHour"></li></ul></div><% }%><div class="time-control fn-left"><div class="calendar-type cal-toggle"><span class="cal cal-type-item active" data-caltype="cal" >公历</span><span class="lunar cal-type-item" data-caltype="lunar">农历</span></div><ul class="cal-lunar-info border-box mt15 clearfix"><li class="cal-picker-ctrl control-bar year-bar" data-send="year" style=""><p class="cal" data-caltype="cal"><span data-fill="year"></span><i></i></p><p class="lunar" data-caltype="lunar"><span data-fill="lunarYear"></span><i></i></p>年</li><li class="cal-picker-ctrl control-bar mouth-bar" data-send="month"><p class="cal" data-caltype="cal"><span data-fill="month"></span><i></i></p><p class="lunar" data-caltype="lunar"><span data-fill="lunarMonthName"></span><i></i></p>月</li><li class="cal-picker-ctrl control-bar day-bar" data-send="day"><p class="cal" data-caltype="cal"><span data-fill="day"></span><i></i></p><p class="lunar" data-caltype="lunar"><span data-fill="lunarDayName"></span><i></i></p>日</li><li class="cal-picker-ctrl control-bar time-bar" data-send="hour"><p style="display:inline-block;"><span class="detail-hour" data-fill="datailHour"></span><i></i></p>时</li><div class="clearfix"></div></ul></div><div class="clearfix"></div></div>';

tpls.tpls_calendar = '<div class="dates clearfix datetimepicker"><div class="datetimepicker-top" data-acpt="top"><a href="javascript:;" class="date-slider-btn prev-btn"><i class="icon-arrow-left"></i></a><a href="javascript:;" class="picker-cur-datetime"></a><a href="javascript:;" class="date-slider-btn next-btn"><i class="icon-arrow-right"></i></a></div><div class="datetime-pannels-box"><div class="dates-tb datetimepicker-years" data-acpt="year"></div><div class="dates-tb datetimepicker-months"  data-acpt="month"></div><div class="dates-tb datetimepicker-days" data-acpt="day"></div><div class="dates-tb datetimepicker-hours" data-acpt="hour"></div></div></div>';

